#!/usr/bin/env python3
"""tickets.py: a small agile board for the agentic environment (P20260926002233: "agile ticketing development system").

    python scripts/tickets.py list [--status S] [--label L]     the board (also regenerated into TICKETS.md)
    python scripts/tickets.py show T-ID
    python scripts/tickets.py add T-ID "title" --prompts P... --owns FILE... [--deps T-ID...] [--label L...] [--gate "..."] [--status S]
    python scripts/tickets.py move T-ID STATUS [--owner NAME] [--note "..."]
    python scripts/tickets.py ready                              tickets that can start now (deps done, no file conflict)
    python scripts/tickets.py check                              exit 1 if two `doing` tickets own the same file

Statuses: backlog -> ready -> doing -> review -> done   (blocked at any point).
Rules it enforces: one writer per file (`owns` may not overlap between `doing` tickets; a trailing `/` owns a directory);
a ticket cannot go `done` without a `gate` result recorded via --note; every ticket cites the prompts (P-ids from PROMPTS.md)
that justify it, or says `agent-idea`. Other windows add their own tickets; the board is the shared picture of who is
writing what. data/tickets/board.json is the source; TICKETS.md is generated and never hand-edited.
"""
import argparse, io, json, os, sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = os.path.join(ROOT, "data", "tickets", "board.json")
VIEW = os.path.join(ROOT, "TICKETS.md")
STATUSES = ["backlog", "ready", "doing", "review", "done", "blocked"]


def load():
    if not os.path.exists(BOARD):
        return {"tickets": []}
    with io.open(BOARD, encoding="utf-8") as fh:
        return json.load(fh)


def save(b):
    os.makedirs(os.path.dirname(BOARD), exist_ok=True)
    with io.open(BOARD, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(b, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    lines = ["# TICKETS (generated by scripts/tickets.py from data/tickets/board.json; do not edit)", "",
             "Updated %s. Rules and commands: `python scripts/tickets.py --help`. Prompts behind each ticket: `PROMPTS.md`." % datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), ""]
    for s in ["doing", "review", "ready", "blocked", "backlog", "done"]:
        ts = [t for t in b["tickets"] if t["status"] == s]
        if not ts:
            continue
        lines += ["## %s (%d)" % (s, len(ts)), "", "| id | title | owner | owns | depends on | prompts | labels |", "|---|---|---|---|---|---|---|"]
        for t in ts:
            lines.append("| %s | %s | %s | %s | %s | %s | %s |" % (t["id"], t["title"].replace("|", "/"), t.get("owner", ""), ", ".join(t.get("owns", [])),
                         ", ".join(t.get("deps", [])), ", ".join(t.get("prompts", [])) or "agent-idea", ", ".join(t.get("labels", []))))
        lines.append("")
    with io.open(VIEW, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))


def overlap(a, b):
    a, b = a.replace("\\", "/"), b.replace("\\", "/")
    return a == b or (a.endswith("/") and b.startswith(a)) or (b.endswith("/") and a.startswith(b))


def conflicts(b, doing_only=True):
    out = []
    ts = [t for t in b["tickets"] if (t["status"] == "doing" or not doing_only)]
    for i, x in enumerate(ts):
        for y in ts[i + 1:]:
            for f in x.get("owns", []):
                for g in y.get("owns", []):
                    if overlap(f, g):
                        out.append((x["id"], y["id"], f, g))
    return out


def find(b, tid):
    for t in b["tickets"]:
        if t["id"] == tid:
            return t
    raise SystemExit("no ticket %s" % tid)


def can_start(b, t):
    done = {x["id"] for x in b["tickets"] if x["status"] == "done"}
    if any(d not in done for d in t.get("deps", [])):
        return False, "dependencies not done"
    for x in b["tickets"]:
        if x["status"] == "doing" and x["id"] != t["id"]:
            for f in t.get("owns", []):
                for g in x.get("owns", []):
                    if overlap(f, g):
                        return False, "file %s is owned by %s" % (f, x["id"])
    return True, ""


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("list"); s.add_argument("--status"); s.add_argument("--label")
    s = sub.add_parser("show"); s.add_argument("id")
    s = sub.add_parser("add"); s.add_argument("id"); s.add_argument("title")
    s.add_argument("--prompts", nargs="*", default=[]); s.add_argument("--owns", nargs="*", default=[]); s.add_argument("--deps", nargs="*", default=[])
    s.add_argument("--label", nargs="*", default=[]); s.add_argument("--gate", default=""); s.add_argument("--status", default="backlog"); s.add_argument("--owner", default="")
    s = sub.add_parser("move"); s.add_argument("id"); s.add_argument("status", choices=STATUSES); s.add_argument("--owner"); s.add_argument("--note")
    sub.add_parser("ready"); sub.add_parser("check")
    a = ap.parse_args()
    b = load()
    if a.cmd == "list":
        for t in b["tickets"]:
            if (not a.status or t["status"] == a.status) and (not a.label or a.label in t.get("labels", [])):
                print("%-10s %-8s %-14s %s" % (t["id"], t["status"], t.get("owner", "")[:14], t["title"]))
        save(b)
    elif a.cmd == "show":
        print(json.dumps(find(b, a.id), indent=1, ensure_ascii=False))
    elif a.cmd == "add":
        if any(t["id"] == a.id for t in b["tickets"]):
            raise SystemExit("exists: %s" % a.id)
        b["tickets"].append({"id": a.id, "title": a.title, "status": a.status, "prompts": a.prompts, "owns": a.owns, "deps": a.deps,
                             "labels": a.label, "gate": a.gate, "owner": a.owner, "history": [[datetime.now(timezone.utc).isoformat(timespec="seconds"), a.status, "created"]]})
        save(b); print("added", a.id)
    elif a.cmd == "move":
        t = find(b, a.id)
        if a.status == "doing":
            ok, why = can_start(b, t)
            if not ok:
                raise SystemExit("cannot start %s: %s" % (a.id, why))
        if a.status == "done" and not (a.note and a.note.strip()):
            raise SystemExit("done needs --note with the gate result (quote the command output, say what is unverified)")
        t["status"] = a.status
        if a.owner is not None:
            t["owner"] = a.owner
        t.setdefault("history", []).append([datetime.now(timezone.utc).isoformat(timespec="seconds"), a.status, a.note or ""])
        save(b); print("%s -> %s" % (a.id, a.status))
    elif a.cmd == "ready":
        for t in b["tickets"]:
            if t["status"] in ("backlog", "ready"):
                ok, why = can_start(b, t)
                print("%-10s %s  %s" % (t["id"], "READY  " if ok else "waiting", t["title"] if ok else why))
    elif a.cmd == "check":
        c = conflicts(b)
        for x in c:
            print("CONFLICT %s and %s both own %s / %s" % x)
        print("%d conflict(s)" % len(c))
        return 1 if c else 0
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.exit(main())
